import Foundation
import SwiftParser
import SwiftSyntax

guard CommandLine.arguments.count >= 2 else {
    fatalError("Usage: PearfyDiscoveryGenerator <output.swift> [source.swift ...]")
}

let outputURL = URL(fileURLWithPath: CommandLine.arguments[1])
let sourceURLs = CommandLine.arguments.dropFirst(2).map(URL.init(fileURLWithPath:))

var components: Set<String> = []
var entities: Set<String> = []
var contractModels: Set<String> = []
for sourceURL in sourceURLs {
    let source = try String(contentsOf: sourceURL, encoding: .utf8)
    let syntax = Parser.parse(source: source)
    for item in syntax.statements {
        if let declaration = item.item.as(StructDeclSyntax.self) {
            if isComponent(declaration.attributes) { components.insert(declaration.name.text) }
            if isEntity(declaration.attributes) { entities.insert(declaration.name.text) }
            if isContractModel(declaration.attributes) { contractModels.insert(declaration.name.text) }
        } else if let declaration = item.item.as(ClassDeclSyntax.self), isComponent(declaration.attributes) {
            components.insert(declaration.name.text)
        } else if let declaration = item.item.as(ActorDeclSyntax.self), isComponent(declaration.attributes) {
            components.insert(declaration.name.text)
        }
    }
}

let registrations = components.sorted().map { "        try await \($0).__pearfy_register(into: container)" }
let body = registrations.joined(separator: "\n")
var generatedImports = ["import PearfyDI"]
if !entities.isEmpty { generatedImports.append("import PearfyData") }
if !contractModels.isEmpty { generatedImports.append("import PearfyConnect") }
var schemaMembers: [String] = []
if !entities.isEmpty {
    schemaMembers.append("""
    public static var entities: [PearfyData.SchemaEntity] {
        [\(entities.sorted().map { "\($0).__pearfy_schema" }.joined(separator: ",\n        "))]
    }
    """)
}
if !contractModels.isEmpty {
    schemaMembers.append("""
    public static var contractSchemas: [PearfyConnect.PearfyContractSchema] {
        [\(contractModels.sorted().map { "\($0).__pearfy_contractSchemas" }.joined(separator: ",\n        "))].flatMap { $0 }
    }
    """)
}
let schemaSection = schemaMembers.isEmpty ? "" : """

public enum PearfyGeneratedSchemaRegistry {
    \(schemaMembers.joined(separator: "\n\n    "))
}
"""
let generated = """
// Generated by PearfyDiscoveryPlugin. Do not edit.
\(generatedImports.joined(separator: "\n"))

public enum PearfyGeneratedRegistry {
    public static func registerComponents(in container: PearfyDI.ServiceContainer) async throws {
\(body)
    }
}
\(schemaSection)
"""

try FileManager.default.createDirectory(at: outputURL.deletingLastPathComponent(), withIntermediateDirectories: true)
try generated.write(to: outputURL, atomically: true, encoding: .utf8)

func isComponent(_ attributes: AttributeListSyntax) -> Bool {
    attributes.contains { element in
        guard case .attribute(let attribute) = element,
              let name = attribute.attributeName.trimmedDescription.split(separator: ".").last else {
            return false
        }
        return ["Component", "Service", "Repository"].contains(String(name))
    }
}

func isEntity(_ attributes: AttributeListSyntax) -> Bool {
    attributes.contains { element in
        guard case .attribute(let attribute) = element,
              let name = attribute.attributeName.trimmedDescription.split(separator: ".").last else {
            return false
        }
        return String(name) == "Entity"
    }
}

func isContractModel(_ attributes: AttributeListSyntax) -> Bool {
    attributes.contains { element in
        guard case .attribute(let attribute) = element,
              let name = attribute.attributeName.trimmedDescription.split(separator: ".").last else {
            return false
        }
        return String(name) == "ContractModel"
    }
}
